---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ac
  name: ac
---
apiVersion: v1
data:
  application.properties: YXBwLmFwaS5rZXk9ZGV2Cg==
kind: Secret
metadata:
  name: api
  namespace: ac
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ac
  name: ac
  namespace: ac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ac
    spec:
      containers:
      - image: anantac/celonis_challenge:1
        imagePullPolicy: IfNotPresent
        name: celonis-challenge
        volumeMounts:
        - name: secret-volume
          mountPath: /app/src/main/resources/
      volumes:
      - name: secret-volume
        secret:
          secretName: api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ac
  name: ac
  namespace: ac
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ac
  type: ClusterIP      
